services:
  postgres:
    image: postgres:16-alpine
    container_name: indora_db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=indora_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: