server:
  port: 8080

auth:
  jwtSecret: PZTpk3by4ybNqGO/A6BU1dysEcP2e7To9dKmAbgsEsa2jqLBqvnCsqdAMjHGft6K5JtN4zeoSW4JFswMqpjaVclDSC4W49NaH11seniKz6M=
  jwtExpirationMs: 14400000
spring:
  application:
    name: indora

  datasource:
    url: jdbc:postgresql://localhost:5432/indora_db
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO